# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop"  ]
jobs:
  test_sqlite3:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
          - ruby: 3.0
          ### RAILS VERSION TESTING
          - ruby: 3.0
            gemfile: gemfiles/rails_7.0.sqlite3.gemfile
        env:
          BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

        steps:
          - uses: actions/checkout@v2

          - name: Install ruby
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: "${{ matrix.ruby }}"

          - name: Bundle
            run: |
              gem install bundler
              bundle install
          - name: Run tests
            run: |
              bundle exec rake