# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop"  ]
jobs:
  test_sqlite:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true

      - name: Bundle
        run: |
          gem install bundler
          bundle install

      - name: Set up database schema
        run: |
          chmod u+x bin/rails
          bin/rails db:schema:load

      - name: Run tests
        run: |
          bundle exec rake